/**
 * noShowReviewController.js — task 4.7 review queue for repeated no-shows,
 * task 4.8 (notifyHR on flag) is handled where the flag is created
 * (jobs/closeAttendanceDay.js's flagRepeatedNoShows), not here.
 *
 * Unlike PromotionRequest, there is no manual `create` — every request is
 * systemGenerated by the daily attendance close job. HR/Admin only ever
 * list and review. Reviewing this queue is explicitly NOT a promotion- or
 * leave-style "approve = apply a change" flow: task 4.7 says flag for
 * review, never auto-terminate, so `onApprove` intentionally has no side
 * effect on the employee record. "Approved" here means "HR confirmed the
 * pattern and is following up outside the system" (e.g. a conversation or
 * a written note); "Rejected" means "reviewed, no action needed" (e.g. the
 * no-shows were later explained/excused). Either way nothing about the
 * employee's status changes automatically.
 */

import NoShowReviewModel from "../model/NoShowReview.js";
import { createReviewRequestController } from "../utils/reviewQueue.js";

const POPULATE = [["employee", "name email employeeId"]];

function toClientRequest(doc) {
  if (!doc) return doc;
  const o = typeof doc.toObject === "function" ? doc.toObject() : doc;
  return {
    id: String(o._id),
    employeeId: o.employee ? String(o.employee._id ?? o.employee) : null,
    employeeName: o.employee?.name ?? null,
    employeeCode: o.employee?.employeeId ?? null,
    noShowCount: o.noShowCountAtFlag,
    reason: o.reason ?? "",
    systemGenerated: Boolean(o.systemGenerated),
    flaggedAt: o.flaggedAt,
    status: o.status,
    reviewNote: o.reviewNote ?? "",
    reviewedBy: o.reviewedBy ? String(o.reviewedBy._id ?? o.reviewedBy) : null,
    reviewedAt: o.reviewedAt ?? null,
    createdAt: o.createdAt,
  };
}

const { list, review } = createReviewRequestController({
  Model: NoShowReviewModel,
  resourceLabel: "no-show review",
  populate: POPULATE,
  toClient: toClientRequest,
  // No onApprove side effect — see file header. HR follows up outside the
  // system; this queue only ever records that the review happened.
  notifyEmployee: (decision, request) => {
    if (decision === "approved") {
      return {
        title: "Attendance record reviewed",
        message: `HR reviewed your attendance record and confirmed a pattern of ${request.noShowCountAtFlag} no-show day(s) on file.${request.reviewNote ? ` Note: ${request.reviewNote}` : " Please speak with HR if you have questions."}`,
      };
    }
    return {
      title: "Attendance record reviewed",
      message: `HR reviewed your attendance record. No further action was taken.${request.reviewNote ? ` Note: ${request.reviewNote}` : ""}`,
    };
  },
  employeeLink: "/attendance",
  employeeLinkLabel: "View attendance",
});

const noShowReviewController = { list, review };

export default noShowReviewController;
