/**
 * Start-of-month job (DECISIONS.md D9, D11): get-or-create the month's FX
 * snapshot, then create the month's PayrollPeriod as a draft with payslips
 * generated by the same code the manual endpoint uses. Never approves or
 * pays. A no-op if the period already exists, so it is safe to re-run.
 */

import PayrollPeriodModel from "../model/PayrollPeriod.js";
import PayslipModel from "../model/Payslip.js";
import { standardWorkingDaysInMonth } from "../utils/payrollEngine.js";
import { buildPayslipRows, insertPayslips, periodLabel } from "../utils/payrollGeneration.js";
import { getOrCreateMonthlyFxRate } from "../utils/exchangeRate.js";
import { logAction } from "../utils/auditLog.js";
import { notifyHR } from "../utils/notify.js";

export async function generateMonthlyPayrollDraft({ asOf = new Date() } = {}) {
  const year = asOf.getFullYear();
  const month = asOf.getMonth() + 1;

  const existing = await PayrollPeriodModel.findOne({ year, month });
  if (existing) {
    return {
      year,
      month,
      skipped: true,
      reason: existing.systemGenerated ? "already-drafted" : "already-exists",
      periodId: String(existing._id),
      generated: 0,
    };
  }

  const fxSnapshot = await getOrCreateMonthlyFxRate({ year, month });

  let created = null;
  try {
    created = await PayrollPeriodModel.create({
      year,
      month,
      fxRate: fxSnapshot.rateVndPerUsd,
      fxRateSource: fxSnapshot.source,
      standardWorkingDays: standardWorkingDaysInMonth(year, month),
      note: `Auto-drafted at the start of the month using a ${fxSnapshot.source === "api" ? "live" : "fallback"} FX rate (${fxSnapshot.rateVndPerUsd} VND/USD).`,
      createdBy: null,
      systemGenerated: true,
    });

    const rows = await buildPayslipRows(created);
    if (!rows.length) {
      await PayrollPeriodModel.findByIdAndDelete(created._id);
      return {
        year,
        month,
        skipped: true,
        reason: "no-payable-employees",
        fxRate: fxSnapshot.rateVndPerUsd,
        fxRateSource: fxSnapshot.source,
        generated: 0,
      };
    }

    const generated = await insertPayslips(rows);

    await logAction(
      {},
      {
        action: "created",
        resource: "payroll",
        resourceId: created._id,
        label: `Payroll ${periodLabel(created)} (auto-drafted)`,
        changes: {
          fxRate: { from: null, to: fxSnapshot.rateVndPerUsd },
          fxRateSource: { from: null, to: fxSnapshot.source },
          generated: { from: 0, to: generated },
        },
      },
    );

    await notifyHR({
      title: "Monthly payroll draft ready",
      message:
        `${generated} draft payslip${generated === 1 ? "" : "s"} auto-generated for ${periodLabel(created)} ` +
        `at ${fxSnapshot.rateVndPerUsd} VND/USD (${fxSnapshot.source === "api" ? "live rate" : "fallback rate"}). ` +
        "Review before the 10th-of-month payroll run.",
      titleKey: "monthlyPayrollDraftReady",
      messageKey: "monthlyPayrollDraftReady",
      params: {
        count: generated,
        periodLabel: periodLabel(created),
        rate: fxSnapshot.rateVndPerUsd,
        rateSource: fxSnapshot.source === "api" ? "live" : "fallback",
      },
      category: "payroll",
      link: "/payroll",
      linkLabel: "Review draft",
    });

    return {
      year,
      month,
      skipped: false,
      periodId: String(created._id),
      fxRate: fxSnapshot.rateVndPerUsd,
      fxRateSource: fxSnapshot.source,
      generated,
    };
  } catch (err) {
    if (created?._id) {
      await PayrollPeriodModel.findByIdAndDelete(created._id).catch(() => {});
      await PayslipModel.deleteMany({ period: created._id }).catch(() => {});
    }
    throw err;
  }
}

export default generateMonthlyPayrollDraft;
